// Generated by Iudex GitHubPagesReporter
window.DASHBOARD_CONFIG = {
  "title": "Iudex API Tests - GitHub Pages Example",
  "mode": "static",
  "apiEndpoint": null,
  "generated": "2026-01-29T12:32:31.277Z"
};
